services:
  - type: web
    name: my-backend-app # اسم التطبيق (اختياري غيره زي ما بدك)
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
